//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProjectUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFine
    {
        public int FineId { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<decimal> TotalFine { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblCard tblCard { get; set; }
    }
}
